version: '3.4'

services:
  godjirabackend:
    image: godjirabackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
